import Head from "next/head";
import React, { useState } from "react";
import { AppContext } from "@/contextAPI/context";
import Link from "next/link";

export default function Home() {
  const [users, setUsers] = useState([]);

  const dispatchUserEvent = (actionType, payload) => {
    switch (actionType) {
      case "ADD_USER":
        setUsers([...users, payload.newUser]);
        return;
      case "REMOVE_USER":
        setUsers(users.filter((user) => user.id !== payload.userId));
        return;
      default:
        return;
    }
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@600&display=swap"
          rel="stylesheet"
        />
        
      </Head>
      <AppContext.Provider value={{ users, dispatchUserEvent }}>
        <div>Hello World!</div>
        <Link href="/signup">SignUp</Link>
        <Link href="/login/login">Login</Link>
      </AppContext.Provider>
    </>
  );
}
